#!/usr/bin/env bash
# This is for monitor organization

xrandr --output HDMI-0 --primary
xrandr --output DP-0 --right-of HDMI-0
xrandr --output DP-4 --left-of HDMI-0
xrandr --output DP-0 --rotate right
xrandr --output DP-0 --pos 5120x-480
