#!/usr/bin/env bash

configuration_location="$HOME/.config"

does_not_exist() {
    ! [ -L "$1" ] && [ ! -f "$1" ] && [ ! -d "$1" ]
}

link_configuration_file_to_home() {
    local target="$1"
    local name="$2"
    local dest="$HOME/$name"

    if does_not_exist "$dest"; then
        ln -s  "$target" "$dest"
        echo "Link created to $target from $dest"
    fi
}

link_directory_to_config() {
    local target="$1"
    local name="$2"
    local dest="$configuration_location/$name"
    if does_not_exist "$dest"; then
        ln -s  "$target" "$dest"
        echo "Link created to $target from $dest"
    fi
}

# Checks that base dot directories aren't being symbolically linked
valid_basename() {
    ! [ "$1" = "." ] || [ "$1" = ".." ] || [ "$1" = "*" ]
}

main() {
    local home_path="$PWD/home"
    local config_path="$PWD/.config"
    # Iterate over all the files in home
    for file in "$home_path"/.* "$home_path"/*; do
        # General error checking of base name and wild card file
        if valid_basename "$(basename "$file")" && [ ! "$file" = "$home_path/*" ]; then
            link_configuration_file_to_home "$file" "$(basename $file)"
        fi
    done

  # Iterate over all the directories in .config
  for directory in "$config_path"/.* "$config_path"/*; do
      # General error checking of base name and wild card directory
      if valid_basename "$(basename "$directory")" && [ ! "$directory" = "$config_path/*" ]; then
          link_directory_to_config "$directory" "$(basename $directory)"
      fi
  done
}

main
